version: "3.8"

services:
  client-api:
    build:
      context: ./services/client-api
      dockerfile: Dockerfile
    container_name: blog-client-api
    expose:
      - 8000
    ports:
      - 8001:8000
    environment:
      - MONGO_URI=mongodb://admin:johncena@mongo:27017/blogs?authSource=admin
    depends_on:
      - mongo
    
  client:
    build:
      context: ./services/client/blog-portfolio
      dockerfile: Dockerfile
    container_name: blog-client
    expose:
      - 3000
    depends_on:
      - client-api
  
  admin-api:
    build:
      context: ./services/admin-api
      dockerfile: Dockerfile
    container_name: blog-admin-api
    expose:
      - 8000
    environment:
      - MONGO_URI=mongodb://admin:johncena@mongo:27017/blogs?authSource=admin
    depends_on:
      - mongo
    
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    container_name: blog-gateway
    expose:
      - 8000
    environment:
      - ADMIN_URL=http://admin-api:8000
      - CLIENT_URL=http://client-api:8000
      - RECAPTCHA_SECRET=${RECAPTCHA_SECRET}
    depends_on:
      - admin-api
      - client-api

  mongo:
    image: mongo:4.4.16-rc0-focal
    container_name: blog-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: johncena
    volumes:
      - /mongo-data:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
  
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: blog-nginx
    ports:
      - 80:80
    depends_on:
      - client